### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by xiqxin1** [pmixer/TiSASRec.pytorch#5]
Hi,
Thank you sooo much for this code.
Did you remember how long it takes for one epoch? I'm not sure if there's bug of my implementation.

**Comment by pmixer** [comment]
longer than SASRec.pytorch, but should not take too long, maybe try debugging with help from `import pdb; pdb.set_trace()`

**Comment by xiqxin1** [comment]
Thanks a lot! I'm now debugging it.
